FROM arm64v8/golang:1.16 as builder

WORKDIR /build

COPY . .

RUN CGO_ENABLED=1 GOOS=linux GOARCH=arm64 go build -a -installsuffix cgo -v -o build_artifact_bin

FROM aarch64/alpine:latest

RUN apk add --no-cache ca-certificates

WORKDIR /go

COPY --from=builder /build/build_artifact_bin hdb-bin

RUN chmod 755 /go/hdb-bin
ENTRYPOINT ["/go/hdb-bin"]
