FROM arm64v8/golang:1.16-alpine as builder

WORKDIR /build

COPY . .

RUN apk add librdkafka-dev pkgconf

RUN go build -tags dynamic -v -o build_artifact_bin

FROM aarch64/alpine:latest

RUN apk add --no-cache ca-certificates librdkafka-dev pkgconf

WORKDIR /go

COPY --from=builder /build/build_artifact_bin hdb-bin

RUN chmod 755 /go/hdb-bin
ENTRYPOINT ["/go/hdb-bin"]
