version: 2.1

jobs:
  github-build-and_push:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - checkout
      - run:
          name: Build Image
          command: |
            docker build -t $GHCR_REPOSITORY:$CIRCLE_SHA1 -f Dockerfile.arm64 .
            docker push $GHCR_REPOSITORY:$CIRCLE_SHA1
  
workflows:
  version: 2
  arm64-image-build:
    jobs:
      - github-build-and_push
          #filters:
          #  tags:
          #    only: /^v[0-9]+(\.[0-9]+)*$/
          #  branches:
          #    only: main
          