version: 2.1

jobs:
  github-build-and_push:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Image
          command: env
          #command: docker build -t ghcr.io/$IMAGE_REPO_NAME/arm64:$IMAGE_TAG -f Dockerfile.arm64 .
  
workflows:
  version: 2
  arm64-image-build:
    jobs:
      - github-build-and_push:
          #filters:
          #  tags:
          #    only: /^v[0-9]+(\.[0-9]+)*$/
          #  branches:
          #    only: main
          requires:
            - go-build