
name: Image Build
on:
  create:
    tags:
      - v*

jobs:
  go-build:
    name: Go Binary & Image Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64]
    steps:
      - name: Set version tag
        id: release
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: DockerCompose
        run: docker-compose -f fixtures/docker-compose.yml up -d
      - name: Get Go version
        run: echo "goversion=`egrep -i '^go [1-2][.][0-9]+$' go.mod | sed 's/go //' | sed 's/$/.x/'`" >> $GITHUB_ENV
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.goversion }}
      - name: Run tests
        run: go test -v  -covermode=count ./...
      - name: Build Binary
        run: CGO_ENABLED=1 GOOS=linux GOARCH=${{ matrix.arch }} go build -a -installsuffix cgo -v -o build_artifact_bin
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}
      - name: Build Image
        uses: docker/build-push-action@v2
        with:
          context: ./k8s
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/${{ matrix.arch }}:${{ steps.release.outputs.tag }}
            ghcr.io/${{ github.repository }}/${{ matrix.arch }}:latest
  
        